let title = """
# This file is auto-generated by Generaptor.""".Trim()

#r "nuget: Generaptor, 1.6.1"
open Generaptor
open Generaptor.GitHubActions
open type Generaptor.GitHubActions.Commands

type OperatingSystem =
    | Linux
    | Windows
    | MacOS

type Architecture =
    | X86_64
    | AArch64

let SupportedPlatforms = [
    Linux, X86_64
    MacOS, AArch64
    Windows, X86_64
]

let workflows = [
    let workflow name body = workflow name [
        header title
        yield! body
    ]

    let nuGetCache() = [
        setEnv "NUGET_PACKAGES" "${{ github.workspace }}/.github/nuget-packages"
        step(
            name = "NuGet cache",
            usesSpec = Auto "actions/cache",
            options = Map.ofList [
                "path", "${{ env.NUGET_PACKAGES }}"
                "key", "${{ runner.os }}.nuget.${{ hashFiles('**/*.fsproj') }}"
            ]
        )
    ]
    
    let checkoutAction = Auto "actions/checkout"
    let dotnetSetupAction = Auto "actions/setup-dotnet"

    workflow "main" [
        name "Main"
        onPushTo "main"
        onPullRequestTo "main"
        onSchedule "0 0 * * 6"
        onWorkflowDispatch
        job "main" [
            strategy(failFast = false, matrix = [
                "config", [
                    Map.ofList [
                        "name", "macos"
                        "image", "macos-14"
                    ]
                    Map.ofList [
                        "name", "linux"
                        "image", "ubuntu-24.04"
                    ]
                    Map.ofList [
                        "name", "windows"
                        "image", "windows-2022"
                    ]
                ]
            ])
            jobName "main.${{ matrix.config.name }}"
            runsOn "${{ matrix.config.image }}"
            setEnv "DOTNET_NOLOGO" "1"
            setEnv "DOTNET_CLI_TELEMETRY_OPTOUT" "1"

            step(
                name = "Checkout",
                usesSpec = checkoutAction
            )
            yield! nuGetCache()
            step(
                name = "Set up .NET SDK",
                usesSpec = dotnetSetupAction,
                options = Map.ofList [
                    "dotnet-version", "9.0.x"
                ]
            )
            step(
                name = "Build",
                run = "dotnet build"
            )
            step(
                name = "Test",
                run = "dotnet test --filter Category!=ExcludeCI"
            )
        ]
        job "encoding" [
            runsOn "ubuntu-24.04"
            step(
                usesSpec = checkoutAction
            )
            step(
                name = "Verify encoding",
                shell = "pwsh",
                run = "Scripts/Test-Encoding.ps1"
            )
        ]
        job "verify-code-format" [
            runsOn "ubuntu-24.04"
            
            setEnv "DOTNET_CLI_TELEMETRY_OPTOUT" "1"
            setEnv "DOTNET_NOLOGO" "1"
            
            step(
                name = "Check out the sources",
                usesSpec = checkoutAction
            )
            step(
                name = "Set up .NET SDK",
                usesSpec = dotnetSetupAction
            )
            yield! nuGetCache()
            
            step(
                name = "Install Fantomas",
                run = "dotnet tool install -g fantomas"
            )
            step(
                name = "Verify code format",
                run = "fantomas . --recurse --check"
            )
        ]
        job "verify-workflows" [
            runsOn "ubuntu-24.04"

            setEnv "DOTNET_CLI_TELEMETRY_OPTOUT" "1"
            setEnv "DOTNET_NOLOGO" "1"

            step(
                name = "Check out the sources",
                usesSpec = checkoutAction
            )
            step(
                name = "Set up .NET SDK",
                usesSpec = dotnetSetupAction
            )
            yield! nuGetCache()
            step(
                name = "Verify generated CI definition",
                run = "dotnet fsi ./Scripts/github-actions.fsx verify"
            )
        ]
    ]
]
exit <| EntryPoint.Process fsi.CommandLineArgs workflows
